[package]
name = "justify"
version = "0.1.0"
authors = ["Max Holder <mxhold@gmail.com>"]

[[bin]]
name = "justify"
path = "src/bin.rs"

[dependencies]
rand = "0.3"

[dev-dependencies]
pretty_assertions = "*"
